## Data Processing in Python Final Project

### Authors: Matyáš Tvrz,

In [15]:
# import packages

import json
import pandas as pd
import os
import requests 
import pandas as pd 
import time
import re 
import random 
import folium

In [ ]:
from function_scripts import request_multiple_sreality
df = request_multiple_sreality(1, 10, 'flat', 'rent', locality_region_id=10)

Could not find a suitable TLS CA certificate bundle, invalid path: /Users/matyastvrz/Documents/IES/Year III/Python/Python_final/.venv/lib/python3.14/site-packages/certifi/cacert.pem

TypeError: 'NoneType' object is not subscriptable

In [27]:
df.shape

(189, 27)

In [28]:
df.head()

,labelsReleased,has_panorama,labels,is_auction,labelsAll,seo,exclusively_at_rk,category,has_floor_plan,_embedded,...,hash_id,attractive_offer,price,price_czk,_links,rus,name,region_tip,gps,has_matterport_url
0,"[[], []]",0,[],False,"[[new_building, personal, cellar, parking_lots...","{'category_main_cb': 1, 'category_sub_cb': 16,...",0,1,0,"{'favourite': {'is_favourite': False, '_links'...",...,1921167436,0,14000,"{'value_raw': 14000, 'unit': 'za měsíc', 'name...",{'dynamicDown': [{'href': 'https://d18-a.sdn.c...,False,Pronájem bytu atypické 24 m²,3664579,"{'lat': 50.00847873160269, 'lon': 14.517273268...",False
1,"[[loggia, terrace], []]",0,"[Lodžie, Terasa]",False,"[[new_building, personal, balcony, loggia, ter...","{'category_main_cb': 1, 'category_sub_cb': 6, ...",0,1,1,"{'favourite': {'is_favourite': False, '_links'...",...,850571340,0,44000,"{'value_raw': 44000, 'unit': 'za měsíc', 'name...",{'dynamicDown': [{'href': 'https://d18-a.sdn.c...,False,Pronájem bytu 3+kk 68 m²,0,"{'lat': 50.08831673160269, 'lon': 14.456972268...",False
2,"[[terrace], []]",0,[Terasa],False,"[[new_building, personal, terrace, cellar, ele...","{'category_main_cb': 1, 'category_sub_cb': 4, ...",0,1,1,"{'favourite': {'is_favourite': False, '_links'...",...,1391960140,0,21000,"{'value_raw': 21000, 'unit': 'za měsíc', 'name...",{'dynamicDown': [{'href': 'https://d18-a.sdn.c...,False,Pronájem bytu 2+kk 59 m²,0,"{'lat': 50.07192873160269, 'lon': 14.492034268...",False
3,"[[], []]",0,[],False,"[[new_building, personal, balcony, elevator, f...","{'category_main_cb': 1, 'category_sub_cb': 4, ...",0,1,0,"{'favourite': {'is_favourite': False, '_links'...",...,2693636172,0,21000,"{'value_raw': 21000, 'unit': 'za měsíc', 'name...",{'dynamicDown': [{'href': 'https://d18-a.sdn.c...,False,Pronájem bytu 2+kk 43 m²,0,"{'lat': 50.003465731602695, 'lon': 14.40776826...",False
4,"[[loggia], []]",0,[Lodžie],False,"[[new_building, personal, loggia, brick, eleva...","{'category_main_cb': 1, 'category_sub_cb': 4, ...",0,1,0,"{'favourite': {'is_favourite': False, '_links'...",...,2248319052,0,21000,"{'value_raw': 21000, 'unit': 'za měsíc', 'name...",{'dynamicDown': [{'href': 'https://d18-a.sdn.c...,False,Pronájem bytu 2+kk 41 m²,0,"{'lat': 50.11114773160269, 'lon': 14.497476268...",False

In [29]:
columns_to_keep = ['locality', 'price', 'name', 'gps','hash_id','exclusively_at_rk']
df_clean = df[columns_to_keep].copy()
df_clean.head()

,locality,price,name,gps,hash_id,exclusively_at_rk
0,Praha 4 - Šeberov,14000,Pronájem bytu atypické 24 m²,"{'lat': 50.00847873160269, 'lon': 14.517273268...",1921167436,0
1,Praha 8 - Karlín,44000,Pronájem bytu 3+kk 68 m²,"{'lat': 50.08831673160269, 'lon': 14.456972268...",850571340,0
2,Praha 10 - Strašnice,21000,Pronájem bytu 2+kk 59 m²,"{'lat': 50.07192873160269, 'lon': 14.492034268...",1391960140,0
3,Praha 4 - Modřany,21000,Pronájem bytu 2+kk 43 m²,"{'lat': 50.003465731602695, 'lon': 14.40776826...",2693636172,0
4,Praha 9 - Prosek,21000,Pronájem bytu 2+kk 41 m²,"{'lat': 50.11114773160269, 'lon': 14.497476268...",2248319052,0

In [31]:
df_clean[['lat', 'lon']] = df_clean.gps.apply(lambda x: pd.Series({'lat': x['lat'], 'lon': x['lon']}))
df_clean.head()

,locality,price,name,gps,hash_id,exclusively_at_rk,lat,lon
0,Praha 4 - Šeberov,14000,Pronájem bytu atypické 24 m²,"{'lat': 50.00847873160269, 'lon': 14.517273268...",1921167436,0,50.008479,14.517273
1,Praha 8 - Karlín,44000,Pronájem bytu 3+kk 68 m²,"{'lat': 50.08831673160269, 'lon': 14.456972268...",850571340,0,50.088317,14.456972
2,Praha 10 - Strašnice,21000,Pronájem bytu 2+kk 59 m²,"{'lat': 50.07192873160269, 'lon': 14.492034268...",1391960140,0,50.071929,14.492034
3,Praha 4 - Modřany,21000,Pronájem bytu 2+kk 43 m²,"{'lat': 50.003465731602695, 'lon': 14.40776826...",2693636172,0,50.003466,14.407768
4,Praha 9 - Prosek,21000,Pronájem bytu 2+kk 41 m²,"{'lat': 50.11114773160269, 'lon': 14.497476268...",2248319052,0,50.111148,14.497476

In [ ]:

m = folium.Map(location=(49.75, 15.40), zoom_start = 8)
m.save("footprint.html")

In [13]:
import os


print(os.getcwd())

/Users/matyastvrz/Documents/IES/Year III/Python/Python_final